# Data
path: ./dataset
train: images/train # training images (relative to 'path')
val: images/val # validation images (relative to 'path')

# Number of classes
nc: 2 

# Classes
names:
  0: Roof
  1: Solar